server.port=8085

# PostgreSQL Database Configuration
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ppp1springbootdb-test
#spring.datasource.username=postgres
#spring.datasource.password=Wipro@123
spring.jpa.hibernate.ddl-auto=update

#info
info.project.env=test