server.port=8084

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ppp1springbootdb-dev
#spring.datasource.username=postgres
#spring.datasource.password=Wipro@123
spring.jpa.hibernate.ddl-auto=update
#info
info.project.env=dev