server.port=8083

# PostgreSQL Database Configuration
#spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/ppp1springbootdb
#spring.datasource.username=postgres
#spring.datasource.password=Wipro@123
