spring.application.name=ITP_PP1_Springboot
spring.profiles.active=dev
# PostgreSQL Database Configuration
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Wipro@123

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Optional
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


# Logging Levels
logging.level.root=INFO
logging.level.com.itp=DEBUG

# Console Log Pattern
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Save logs into file
logging.file.name=logs/application.log

