server.port=8086

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/ppp1springbootdb
#spring.datasource.username=postgres
#spring.datasource.password=Wipro@123